name: Run

on:
  workflow_dispatch:
  repository_dispatch:
  schedule:
  # 每天国际时间 0:0 运行一次, 中国时间 8:00
    - cron: '0 0 * * *'

jobs:
  build:

    if: github.actor == github.repository_owner
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main
    - name: Run
      uses: coactions/setup-xvfb@main
      with:
        run: dotnet run
      env: 
        CONF: ${{ secrets.CONF }}
